FROM ghcr.io/ultramarine-linux/ultramarine:44

RUN dnf do -y --action=install \
    cargo \
    ceph-common \
    clang-devel \
    cloud-hypervisor-nightly \
    cmake \
    composefs \
    e2fsprogs \
    fsverity-utils \
    git \
    libvirt-devel \
    ninja \
    openssl-devel \
    rust \
    rustup \
    skopeo \
    util-linux \
    virtiofsd \
    zig

WORKDIR /workspace

CMD ["cargo", "run", "--release", "-p", "odorobo", "--", "--manager-enabled", "true"]
