FROM ghcr.io/ultramarine-linux/ultramarine:44

RUN dnf do -y --action=install \
    cargo \
    ceph-common \
    clang-devel \
    cloud-hypervisor-nightly \
    cmake \
    curl \
    git \
    libvirt-devel \
    ninja \
    protobuf-compiler \
    rust \
    rustup \
    zig

WORKDIR /workspace

CMD ["cargo", "run", "--release", "-p", "odorobo", "--", "--manager-enabled", "true"]
