version: 2

multi-ecosystem-groups:
  cargo:
    schedule:
      interval: daily
  actions:
    schedule:
      interval: weekly

updates:
  # Maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: actions

  # Maintain Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: cargo
