name: Build RISC V RVA23 via x86 cross-compile

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build image
      run: podman build -t odorobo-builder:rva23 .
    - name: Build binaries
      run: podman run --rm -v ${{ github.workspace }}:/code -w /code odorobo-builder:rva23 cargo build --release --verbose
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: odorobo_riscv_rva23
        path: |
          target/riscv64a23-unknown-linux-gnu/release/odorobo-agent
          target/riscv64a23-unknown-linux-gnu/release/odoroboctl
