name: Build x86

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: odorobo_x86
        path: |
          target/release/odorobo-agent
          target/release/odoroboctl
    - name: Run tests
      run: cargo test --verbose
