name: Build x86

on:
  push:
  pull_request:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: rui314/setup-mold@v1
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Build
        run: cargo build --verbose --release
      - name: Upload artifact - agent
        uses: actions/upload-artifact@v7
        with:
          archive: false
          name: odorobo-agent-x86
          path: |
            target/release/odorobo-agent

      - name: Upload artifact - odoroboctl
        uses: actions/upload-artifact@v7
        with:
          archive: false
          name: odoroboctl-x86
          path: |
            target/release/odoroboctl

      - name: Run tests
        run: cargo test --verbose
