name: Build x86

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: rui314/setup-mold@v1
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.9
    
    - name: Build
      run: cargo build --verbose --release
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        archive: false
        name: odorobo_x86
        path: |
          target/release/odorobo-agent
          target/release/odoroboctl
    - name: Run tests
      run: cargo test --verbose
