name: mirror
on: [push]

permissions:
  contents: read

jobs:
  mirror:
    uses: FyraLabs/actions/.github/workflows/mirror.yml@main
    secrets:
      GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
