name: Rust
permissions:
  contents: read
on:
  push:
  workflow_dispatch:

jobs:
  rust:
    permissions:
      security-events: write
      contents: read
      packages: read

    uses: FyraLabs/actions/.github/workflows/rust.yml@main
    with:
      test-pre: sudo dnf update && sudo dnf install -y protobuf-compiler
      test-cache: true
      test-riscv-rva23: true
      test-riscv-builder-image: ghcr.io/fyralabs/rva23-builder@sha256:807797111a49bd11b2a2b0bfcf79cc7be7ea6ab7beb1d38b8871d87961997460

      test-riscv-artifact-name: odorobo-riscv-rva23
      test-riscv-artifact-paths: |
        target/riscv64a23-unknown-linux-gnu/release/odorobo
        target/riscv64a23-unknown-linux-gnu/release/odoroboctl
