name: Rust
permissions:
  contents: read
on:
  push:
  workflow_dispatch:

jobs:
  rust:
    permissions:
      security-events: write
      contents: read
      packages: read

    uses: FyraLabs/actions/.github/workflows/rust.yml@main
    with:
      test-pre: sudo dnf update && sudo dnf install -y protobuf-compiler
      test-cache: true
      test-riscv-rva23: true
      test-riscv-builder-image: ghcr.io/fyralabs/rva23-builder@sha256:a921a5f4674abc5dd7bd2ebcfb9707b52cf2df18c6c2e7302902f5da9e563711

      test-riscv-artifact-name: odorobo-riscv-rva23
      test-riscv-artifact-paths: |
        target/riscv64a23-unknown-linux-gnu/release/odorobo
        target/riscv64a23-unknown-linux-gnu/release/odoroboctl
